<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DOLebedev" name="test.timetest.TimeMethod" tests="2" failures="0" timestamp="20 Jul 2015 17:26:39 GMT" time="0.938" errors="1">
  <testcase name="timeTestOne" time="0.523" classname="test.timetest.TimeMethod">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.timeTestOne() didn&#039;t finish within the time-out 500">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.timeTestOne() didn't finish within the time-out 500
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:57)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- timeTestOne -->
  <testcase name="timeTestTwo" time="0.415" classname="test.timetest.TimeMethod"/>
</testsuite> <!-- test.timetest.TimeMethod -->
